### ISSUE TITLE
LoLo limit not detected in analog-alarm-monitor

### ISSUE THREAD

**Issue by jpdn-Net** [hj91/node-red-contrib-analog-alarm-monitor#2]
Hi,

Using parameters as in the supplied example, the LoLo limit is never checked.
Instead Lo limit takes precedence over the LoLo limit.

- a value  like 220 shows a status as **Lo** , in my opinion, the status should be LoLo  .
Please let me know if I am right or wrong ?

Thanks,
JP

See attached screen copy.
![Screen copy Analog Alarm](https://github.com/hj91/node-red-contrib-analog-alarm-monitor/assets/59450443/67fa517b-5ebd-40e4-a92e-42bb399c499a)

**Comment by hj91** [comment]
Check the screenshot - i did get the LoLo alarm when the value was below LoLo limit. I tested it with limit values set by your example.

![Screenshot from 2024-05-15 16-15-23](https://github.com/hj91/node-red-contrib-analog-alarm-monitor/assets/396344/040df6f2-5de4-4a01-8f66-60821dd643ba)

Please update the node from npm or github to latest version

**Comment by jpdn-Net** [comment]
I have installed this node this morning, using the Manage Palette menu in Nodered, and it was showing this problem wilth LoLo limit.
I think it has loaded version 1.01.

After your message, I have updated the node, with  the Manage Palette, it now shows version 1.03 .

This version works OK , no more problem.

Thank you for your quick reply.

JP
